### ISSUE TITLE
horenso.yml feature

### ISSUE THREAD

**Issue by Songmu** [Songmu/horenso#19]
```yaml
tag: "hoge"
timestamp: true
noticer:
  - 
reporter:
  - 
```

```console
% horenso -- /path/to/cmd
```

何れもオプショナル。コマンドライン上で上書きできる。
